---
- name: Check if systemd exists
  stat: path=/etc/systemd/system/
  register: systemd_check

- name: Systemd script.
  template: src=zookeeper.service.j2 dest=/etc/systemd/system/zookeeper.service
  when: systemd_check.stat.exists == true
  notify:
    - Restart zookeeper
